### ISSUE TITLE
Make more components as optional

### ISSUE THREAD

**Issue by Trq430** [grm34/archboot#141]
The script is very good and I have a few thoughts to select more components individually.  I list them:

**Base system:** base-devil and linux-firmware both as optional (_yes_/_no_)

**Desktop Environment's -> Gnome and xfce:** Gnome-extra and xfce4-goodies both as optional (_yes_/_no_)

**GPU Drivers:** are optional but if choosen, let the Hardware-Acceleration packages optional (_yes_/_no_)

**Set system clock:** set-ntp(true) as optional, so the user can choose to set the clock via internet (_yes_/_no_)

**Fonts:** let the user choose which fonts are wanted -> so it would be possible to only install _ttf-dejavu_ (for exapmple) and not the whole font-family 

Maybe I piqued your interest because customizing is very popular for a lot of users.
Souvent, moins c'est plus ;)

**Comment by grm34** [comment]
Thanks for your feedback :)

* Fonts are removed since a while.

* As you said, GPU drivers are optionals, you can simply select NO and install them later if you don't want hardware acceleration packages. I really want minimal stuff without asking 50 questions to the user and in this case installing driver without hardware acceleration seems little bit useless, using kernel modsetting is enought.

* `timedatectl set-ntp true` is only applied to the live environment, but right service is activated later during base system installation (ntpd)

* Firmware is required, some drivers for system board, network, (...) are in there.

Anyway ntpd and DE extra/goodies will be turned in to optionals and base-devel will be installed only in case of AUR Helper.

**Comment by grm34** [comment]
@Trq430 implemented by https://github.com/grm34/archboot/pull/142

**Comment by Trq430** [comment]
Thank you! That sounds great :)

**Comment by grm34** [comment]
@Trq430 you're welcome ;)

**Comment by ghost** [comment]
@grm34  Unfortunately I had to create a new account at github because there were acute problems with my email provider - but that is now a thing of the past. So I'm writing as Trq430...
You edited your post again, so I'll reply to it again because the content has changed a bit:





>     Firmware is required, some drivers for system board, network, (...) are in there

That is correct, of course, but on the other hand, there are still many systems that absolutely do not need `linux-firmware`. So I would be very happy if you would reconsider your decision. ;)

Something else: Isn't `os-prober` (for systems with BIOS) interesting only when it comes to dual-boot? Otherwise it seems superfluous and interesting as optional. But of course that is in your hands. ;)

**Comment by grm34** [comment]
@At1768 yes sorry edited twice. 

Absolutely many systems doesn't need `linux-firmware`, i'll have a look how to handle this without encountering issues for systems wich need it.
  
Right, `os-prober` is only required by grub to detect non-unix os. Added by default for users wich comes from windows, helpful for them as they will always have the ability to boot on win easily. I'll have a look on this too.

**Comment by grm34** [comment]
@At1768 issue auto closed by PR but let me know, that don't do the trick in case of NTFS partitions without any winOS (rare cases) `ntfs-3g` and `os-prober` will be installed.

**Comment by ghost** [comment]
@grm34 This is excellent news. Thanks for the implementation. ;)
_C'est la perfection_

**Comment by grm34** [comment]
@At1768 you're welcome. I will also remove ntp service wich is not required at all

**Comment by ghost** [comment]
@grm34 Wow, that's a nice surprise to see _Video Hardware Acceleration_ as optional. My enthusiasm for your project never ends. ;)
L'amour l'emportera toujours

**Comment by grm34** [comment]
@At1768  ahah espérons!

**Comment by ghost** [comment]
@grm34 Hey, I have now completed the translation into German and you can use it if you like. ;) Unfortunately I am not very familiar with github, so I am writing here.

Then I wanted to ask if your decision to remove ntp completely still exists? I ask because it is no longer listed in the wiki and is still active in your script.

**Comment by grm34** [comment]
@At1768 thanks a lot for your support, good job! German will be implemented soon!

Yes `ntp` was removed and not installed anymore. The part of code you are talking about is only applied to **live system** to properly define clock before running install.

**Comment by ghost** [comment]
@grm34  



> only applied to **live system**

Yes exactly, at this point I was also mentally and understood it so that it was initially available as optional (live system) and then completely removed (live system). But no problem, then I will open port 123 UDP in the router. Hopefully other users, whose port is blocked, will also think of it, otherwise the script will stop at this point.

**Comment by grm34** [comment]
Hm I see, which error code is displayed `Error: ntpd -qg` or `Error: timedatectl set-ntp true` ?

For german i saw your fork and didn't see any german file in locale folder, see [Contributing](https://github.com/grm34/archboot/blob/master/.github/CONTRIBUTING.md) for help, or join [Telegram group](t.me/archboot) ;)

**Comment by ghost** [comment]
@grm34 


> Hm I see, which error code is displayed `Error: ntpd -qg` or `Error: timedatectl set-ntp true` ?

No error message appears, but the script remains at this point (exactly when the ntp operation is performed). I waited about 30 seconds and then canceled the process myself.



> Timedatectl error if 123 UDP port is **_open_** #194 

But the error occurs when the port is **_closed_** (like I reported earlier), or have you already tested it with the port _open_ and the error or stopping the process happens anyway ?

**Comment by grm34** [comment]
@At1768 ok i see exactly your problem, please can you copy/paste your last post to the refered issue?
I'm sorry about strict guidelines but that helps other understand what happen to the code.

Thanks a lot for your traduction, i implement it right now. Some new lines added since, could you please have a look when trad will be pushed?

Edit:

MSG_INTERNET="Checking Internet connection"
MSG_ERROR_GIT="do not run archboot from git repository folder!"

Thanks!

**Comment by ghost** [comment]
@grm34 


> Some new lines added since, could you please have a look when trad will be pushed?

done! Gladly again anytime ;)




> please can you copy/paste your last post to the refered issue?

I will open the port in my router tomorrow, perform an Install of _Archboot_ and then report to the refered issue. I would like to check that before I write. Then I'll report in more detail. Because so far I have not yet performed an install with the port open (123 UDP).


> I'm sorry about strict guidelines but that helps other understand what happen to the code.

That is absolutely fine! I will always do this in the future.

**Comment by At1768** [comment]
@grm34 





> join [Telegram group](t.me/archboot) ;)

big sorry for my silence. Unfortunately I am not at telegram but would of course like to get in touch with you more than before. Please don't be disappointed. Please give me some time to register with telegram. There's a lot going on in reallife right now. I hope for your understanding.

I will also delete this message shortly because offtopic, which unfortunately has happened to me too often. sry
